name: Build & Publish Docker image (Jib)

on:
  push:
    branches: [ "main", "cleanup" ]
  workflow_dispatch: {}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "${{ properties.java.version }}"
          cache: maven

      - name: Run tests
        run: mvn -B test jacoco:report

      - name: Build, test, coverage, SonarCloud analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn -B verify sonar:sonar \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.organization=kalpak44 \
            -Dsonar.projectKey=bunker-party \
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml


      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push image with Jib (latest + git sha)
        run: |
          mvn -B package jib:build \
            -Djib.to.image=${{ secrets.DOCKERHUB_USERNAME }}/bunker-party \
            -Djib.to.tags=latest,${{ github.sha }}
